source("make_graphs.R")
my.data <- process.power.data("pared_down_data.csv")
png(file="plot3.png")
plot(as.POSIXct(paste(my.data$date, my.data$time)), my.data$sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
lines(as.POSIXct(paste(my.data$date, my.data$time)), my.data$sub_metering_2, type="l", col="red")
lines(as.POSIXct(paste(my.data$date, my.data$time)), my.data$sub_metering_3, type="l", col="purple")
legend("topright", lty="solid", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "purple"))
dev.off()
